SistemaPrestamos/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SistemaPrestamos.Models
{
    public class Cliente
    {
        public int ClienteID { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        [Required]
        [EmailAddress]
        public string Correo { get; set; }
        [Required]
        public string Direccion { get; set; }
    }
}

SistemaPrestamos/Models/Prestamo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SistemaPrestamos.Models
{
    public class Prestamo
    {
        [Key]
        public int PrestamoID { get; set; }
        [Required]
        public int Plazo { get; set; }
        [Required]
        public double Interes { get; set; }
        [Required]
        public double CantidadPrestada { get; set; }

        public double Cuota { get; set; }

        //[DataType(DataType.Date)]
        public DateTime  IniciodePrestamo { get; set; }

        [Required]
        public int IdCliente { get; set; }
    }
}

SistemaPrestamos/Models/PrestamosDB.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace SistemaPrestamos.Models
{
    public class PrestamosDB: DbContext 
    {
        public DbSet<Cliente> cliente { get; set; }
        public DbSet<Prestamo> prestar { get; set; }
    }
}

SistemaPrestamos/Controllers/ClienteController.cs
using SistemaPrestamos.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaPrestamos.Controllers
{
    public class ClienteController : Controller
    {
        [HttpPost]
        public JsonResult CreatePerson()
        {
            using (var db = new PrestamosDB())
                try
                {
                    var result = db.cliente.ToList();
                    return Json(new { Result = "OK", Records = result });
                }
                catch (Exception ex)
                {
                    return Json(new { Result = "ERROR", Message = ex.Message });
                }
        }

        public ActionResult Index()
        {
            return View();
        }

        //metedo en donde se crearan nuevos prestamos 
        [HttpPost]
        public JsonResult Create(Cliente cliente)
        {
            using (var db = new PrestamosDB())

                try
                {
                    if (!ModelState.IsValid)
                    {
                        return Json(new
                        {
                            Result = "ERROR",
                            Message = "Form is not valid! " +
                          "Please correct it and try again."
                        });
                    }

                    var addPres = db.cliente.Add(cliente);
                    db.SaveChanges();
                    return Json(new { Result = "OK", Record = addPres });
                }
                catch (Exception ex)
                {
                    return Json(new { Result = "ERROR", Message = ex.Message });
                }
        }

        //metodo para modificar los prestamos 
        [HttpPost]
        public JsonResult Update(Cliente cliente)
        {
            using (var db = new PrestamosDB())

                try
                {
                    if (!ModelState.IsValid)
                    {
                        return Json(new
                        {
                            Result = "ERROR",
                            Message = "Form is not valid! " +
                            "Please correct it and try again."
                        });
                    }

                    db.Entry(cliente).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { Result = "OK" });
                }
                catch (Exception ex)
                {
                    return Json(new { Result = "ERROR", Message = ex.Message });
                }
        }

        //metodo utilizado para eliminar prestamos 
        [HttpPost]
        public JsonResult Delete(int ClienteID)
        {
            using (var db = new PrestamosDB())

                try
                {
                    var result = db.cliente.Find(ClienteID);
                    db.cliente.Remove(result);
                    db.SaveChanges();
                    return Json(new { Result = "OK" });
                }
                catch (Exception ex)
                {
                    return Json(new { Result = "ERROR", Message = ex.Message });
                }
        }



    }
}

SistemaPrestamos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaPrestamos.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SistemaPrestamos/Controllers/PrestamoController.cs
using SistemaPrestamos.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaPrestamos.Controllers
{
    public class PrestamoController : Controller
    {
        //listado de prestamos
        [HttpPost]
        public JsonResult ListadoPrestamos()
        {
            using (var db = new PrestamosDB())
                try
                {
                    var result = db.prestar.ToList();
                    return Json(new { Result = "OK", Records = result });
                }
                catch (Exception ex)
                {
                    return Json(new { Result = "ERROR", Message = ex.Message });
                }
        }

        public ActionResult Index()
        {
            return View();
        }

        //creacion de prestamos
        [HttpPost]
        public JsonResult CrearPrestamos(Prestamo pres)
        {
            using (var db = new PrestamosDB())

                try
                {
                    if (!ModelState.IsValid)
                    {
                        return Json(new
                        {
                            Result = "ERROR",
                            Message = "Form is not valid! " +
                          "Please correct it and try again."
                        });
                    }

                    var addPres = db.prestar.Add(pres);
                    db.SaveChanges(); // Esto es lo que guarda en la base de datos

                    return Json(new { Result = "OK", Record = addPres });
                }
                catch (Exception ex)
                {
                    return Json(new { Result = "ERROR", Message = ex.Message });
                }
        }

        //modificacion de prestamos
        [HttpPost]
        public JsonResult ModificarPrestamo(Prestamo pres)
        {
            using (var db = new PrestamosDB())

                try
                {
                    if (!ModelState.IsValid)
                    {
                        return Json(new
                        {
                            Result = "ERROR",
                            Message = "Form is not valid! " +
                            "Please correct it and try again."
                        });
                    }

                    db.Entry(pres).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { Result = "OK" });
                }
                catch (Exception ex)
                {
                    return Json(new { Result = "ERROR", Message = ex.Message });
                }
        }

        //eliminar prestamos
        [HttpPost]
        public JsonResult EliminarPrestamo(int prestarID)
        {
            using (var db = new PrestamosDB())

                try
                {
                    var result = db.prestar.Find(prestarID);
                    db.prestar.Remove(result);
                    db.SaveChanges();
                    return Json(new { Result = "OK" });
                }
                catch (Exception ex)
                {
                    return Json(new { Result = "ERROR", Message = ex.Message });
                }
        }


    }
}

SistemaPrestamos/Views/Cliente/Index.cshtml
@{  
    ViewBag.Title = "Clientes";
    Layout = "~/Views/Shared/_Layout1.cshtml";

}

<h2>Clientes</h2>

<div id="TablaCliente" style="width: auto; margin:auto;"></div>

<script type="text/javascript">

    $(document).ready(function () {

        //Prepare jtable plugin
        $('#TablaCliente').jtable({
            title: 'Listado de cliente',
            //paging: true,
            actions: {
                listAction: '/Cliente/CreatePerson',
                createAction: '/Cliente/Create',
                updateAction: '/Cliente/Update',
                deleteAction: '/Cliente/Delete'
            },
            fields: {
                ClienteID: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                Nombre: {
                    title: 'Nombre',
                    width: '15%',
                    list: true
                },
                Apellido: {
                    title: 'Apellido',
                    width: '15%'
                },
                Telefono: {
                    title: 'Telefono',
                    width: '15%'
                },
                Correo: {
                    title: 'Correo',
                    width: '15%'
                },
                Direccion: {
                    title: 'Direccion',
                    width: '15%'
                }
            }
        });

        //Load person list from server
        $('#TablaCliente').jtable('load');
    });

</script>
<div>
    @Html.ActionLink("Ver Prestamos", "Index","Prestamo")
</div>

SistemaPrestamos/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SistemaPrestamos/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SistemaPrestamos/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SistemaPrestamos/Views/Prestamo/Index.cshtml
@{
    ViewBag.Title = "Prestamos ";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Prestamos</h2>

<div id="TablaPrestamo" style="width: auto; margin:auto;"></div>

<script type="text/javascript">

    $(document).ready(function () {

        //Prepare jtable plugin
        $('#TablaPrestamo').jtable({
            title: 'Listado de Prestamos',
            actions: {
                listAction: '/Prestamo/ListadoPrestamos',
                createAction: '/Prestamo/CrearPrestamos',
                updateAction: '/Prestamo/ModificarPrestamo',
                deleteAction: '/Prestamo/EliminarPrestamo'
            },
            fields: {
                PrestamoID: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                NombreCliente: {
                    title: 'Cliente ID',
                    width: '15%',
                    list: true
                },
                Cantidad: {
                    title: 'Cantidad Prestada',
                    width: '25%',
                    list: true
                },
                Interes: {
                    title: 'Interes',
                    width: '15%',
                    list: true
                },
                Plazo: {
                    title: 'Plazo',
                    width: '15%',
                    list: true
                },
                Cuota: {
                    title: 'Cuota',
                    width: '15%',
                    list: true
                },
                inicioPrestamo: {
                    title: 'Inicio del prestamos',
                    width: '30%',
                    list: true
                }
            }
        });

        //Load person list from server
        $('#TablaPrestamo').jtable('load');
    });

</script>
<div>
    @Html.ActionLink("Ver Clientes", "Index", "Cliente")
</div>

SistemaPrestamos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SistemaPrestamos/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
@{
    var jTableStyle = "metro/blue/jtable.css";
    if (!string.IsNullOrEmpty(Request["jTableStyle"]))
    {
        jTableStyle = Request["jTableStyle"];
    }
}
<html>
<head>
    <meta charset="utf-8" />
    <title>Sistemas de Prestamos 
    </title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/redmond/jquery-ui-1.8.16.custom.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/highlight.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Scripts/jtable/themes/" + jTableStyle)" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/Scripts/syntaxhighligher/styles/shCore.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Scripts/syntaxhighligher/styles/shThemeDefault.css")" rel="stylesheet" type="text/css" />
    
    @RenderSection("CssImport", false)
    
    <script src="@Url.Content("~/Scripts/jquery-1.6.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/syntaxhighligher/shCore.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/syntaxhighligher/shBrushJScript.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/syntaxhighligher/shBrushXml.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/syntaxhighligher/shBrushCSharp.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/syntaxhighligher/shBrushSql.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/jtablesite.js")" type="text/javascript"></script>
        
    <script type="text/javascript" src="@Url.Content("~/Scripts/jtable/jquery.jtable.js")"></script>
    
    @RenderSection("JavascriptImport", false)    
</head>
<body>
    <div class="site-container">
        <div class="content-container">
            @RenderBody()
            
            @*<div style="margin-top: 12px">See <b><a href="http://www.jtable.org">jtable.org</a></b> for latest demos and documantation.</div>*@
        </div>
    </div>
</body>
</html>